services:
  # A Python web service
  - type: web
    name: www
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash ./render.sh
    envVars:
      - key: ADDR
        fromGroup: bot
      - key: PASSWORD
        fromGroup: bot
      - key: ADMIN
        fromGroup: bot
      - key: BOT_NAME
        fromGroup: bot
      - key: DELAY
        fromGroup: bot
